bot:
    name:  ${TELEGRAMBOT_NAME}
    token: ${TELEGRAMBOT_TOKEN}
spring:
  application:
    name: bot-service
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/telegrambot
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:}
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          temp:
            use_jdbc_metadata_defaults: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

