server:
  port: 8081
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eventservice
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASS:}
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          temp:
            use_jdbc_metadata_defaults: false
    flyway:
      baseline-on-migrate: true