spring:
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:./data/event-service;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
      username: sa
      password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect:  org.hibernate.dialect.MySQL8Dialect
          default_schema: 'public'
          temp:
            use_jdbc_metadata_defaults: false